db.students.insert({name: "Ryan", home_state: "La", lucky_number: 9, birthday:{month: 8, day: 1, year: 1986}})
db.students.insert({name: "Terry", home_state: "La", lucky_number: 10, birthday:{month:8 , day: 8, year: 1956}})
db.students.insert({name: "Carla", home_state: "Wa", lucky_number: 11, birthday:{month: 1 , day: 2, year: 3}})
db.students.insert({name: "Max", home_state: "SC", lucky_number: 12, birthday:{month: 4, day: 5, year: 6}})
db.students.insert({name: "Steven", home_state: "NC", lucky_number: 13, birthday:{month: 7, day: 8, year: 9}})
db.students.find({})
db.students.find({name: "Trey"})
db.students.find({home_state:"Ca"})
db.students.find({home_state:"Wa"})
db.students.find({lucky_number: 10})
db.students.find({lucky_number: {$gt: 10}})
db.students.find({$and: [{lucky_number: {$gte:1}},{lucky_number: {$lte:9}}]})
db.students.update({name:"Steven"},{$push:{interests:'basketball'}})
db.students.update({name:"Max"},{$push:{interests:'taxes'}})
db.students.update({name:"Max"}, {$pull:{interests:'taxes'}})
db.students.remove({home_state:"CA"})
db.students.remove({name:"Steven"},true)
db.students.remove({lucky_number:{$gt:5}},true)
db.students.updateMany( {},{ $set:{ number_of_belts: 0 } } )
db.students.updateMany({home_state:"Wa"},{ $inc:{ number_of_belts: 1 } } )
db.students.updateMany( {}, { $rename:{'number_of_belts': 'belts earned'}} )
db.students.updateMany({},{$unset:{lucky_number:""}})
db.students.updateMany({},{$currentDate:{updated_on:{$type:"date"}}})